local builtin = require("telescope.builtin")
vim.keymap.set("n", "<C-f>", builtin.find_files, {})
vim.keymap.set("n", "<C-w>", builtin.live_grep, {})
vim.keymap.set("n", "<C-R>", builtin.resume, {})
vim.keymap.set("n", "<C-b>", builtin.buffers, {})
vim.keymap.set("n", "<leader>gs", function()
	builtin.grep_string({ search = vim.fn.input("Grep> ") })
end)
